/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IngresoRouteImport } from './routes/ingreso'

const IngresoRoute = IngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/ingreso': typeof IngresoRoute
}
export interface FileRoutesByTo {
  '/ingreso': typeof IngresoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ingreso': typeof IngresoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/ingreso'
  fileRoutesByTo: FileRoutesByTo
  to: '/ingreso'
  id: '__root__' | '/ingreso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IngresoRoute: typeof IngresoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ingreso': {
      id: '/ingreso'
      path: '/ingreso'
      fullPath: '/ingreso'
      preLoaderRoute: typeof IngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IngresoRoute: IngresoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
